# Generated by Django 3.0.5 on 2020-04-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilelanguage',
            name='tutor',
            field=models.BooleanField(default=False, verbose_name='can co-host'),
        ),
    ]
