# Generated by Django 3.0.5 on 2020-05-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200423_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_language',
            field=models.CharField(default='tr', max_length=8, verbose_name='profile language'),
        ),
    ]
