# Generated by Django 3.0.5 on 2020-04-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meetingpoll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingparticipant',
            name='tutor',
            field=models.BooleanField(default=False, verbose_name='co-host'),
        ),
        migrations.AlterField(
            model_name='meetingrequest',
            name='tutor',
            field=models.BooleanField(choices=[(False, 'Practice the language'), (True, 'Co-host the session')], default=False, verbose_name='co-host'),
        ),
    ]
