# Generated by Django 3.0.5 on 2020-04-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20200424_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='cancellation_reason',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'no host'), (2, 'no participant'), (0, 'other')], null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'practice'), (2, 'community meeting')], default=1, verbose_name='meeting type'),
        ),
    ]
