# Generated by Django 3.0.5 on 2020-05-03 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('meetings', '0007_auto_20200502_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_file',
        ),
        migrations.AddField(
            model_name='document',
            name='language',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='languages.Language', verbose_name='language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='level',
            field=models.CharField(blank=True, choices=[('A', 'I can catch some words in texts or speeches. From time to time, by combining these words, I can grasp the context and the general meaning, but I cannot get a complete idea of the content of the text / speech; I have a hard time speaking / I cannot speak.'), ('B', 'When I read simple texts, I can get a rough idea of the general subject; I can understand the main idea of slow and clear conversations; I cannot understand complex texts or speeches; I have difficulty speaking / I cannot speak.'), ('C', 'I can understand texts / speeches mostly unless they are complex, but I want to grasp more and master the whole. I can speak slowly with a limited vocabulary, I want to be fluent, improve my vocabulary')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
    ]
