# Generated by Django 3.0.5 on 2020-05-03 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0008_auto_20200503_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('type', models.CharField(choices=[('r', 'reading'), ('l', 'listening'), ('w', 'watching')], max_length=1, verbose_name='resource type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('level', models.CharField(blank=True, choices=[('A', 'I can catch some words in texts or speeches. From time to time, by combining these words, I can grasp the context and the general meaning, but I cannot get a complete idea of the content of the text / speech; I have a hard time speaking / I cannot speak.'), ('B', 'When I read simple texts, I can get a rough idea of the general subject; I can understand the main idea of slow and clear conversations; I cannot understand complex texts or speeches; I have difficulty speaking / I cannot speak.'), ('C', 'I can understand texts / speeches mostly unless they are complex, but I want to grasp more and master the whole. I can speak slowly with a limited vocabulary, I want to be fluent, improve my vocabulary')], max_length=1, null=True, verbose_name='level')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.Language', verbose_name='language')),
            ],
        ),
        migrations.RemoveField(
            model_name='meetingdocument',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='meetingdocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='meetingdocument',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='documents',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='MeetingDocument',
        ),
        migrations.AddField(
            model_name='meetingresource',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting', verbose_name='meeting'),
        ),
        migrations.AddField(
            model_name='meetingresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Resource', verbose_name='resource'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='resources',
            field=models.ManyToManyField(through='meetings.MeetingResource', to='meetings.Resource', verbose_name='meeting resource'),
        ),
    ]
