# Generated by Django 3.0.5 on 2020-05-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_auto_20200508_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(default='-', max_length=50, verbose_name='title'),
            preserve_default=False,
        ),
    ]
